---
title: "About"
---

## Education:

### Bocconi University

I am presently a second year student pursuing the [MSc in Economic and Social Sciences](https://www.unibocconi.eu/wps/wcm/connect/bocconi/sitopubblico_en/navigation+tree/home/programs/master+of+science/economic+and+social+sciences/) at Bocconi University. I am selected in the [ICRIOS](https://icrios.unibocconi.eu/) Visiting Students Program (2023-2024), where we are mentored and trained in empirical research methods. I have completed courses like advanced statistics, advanced mathematics, advanced macroeconomics, macroeconometrics, development economics, economic analysis of crime, population dynamics, and labour economics. My thesis with Prof. [Arnstein Aassve](https://faculty.unibocconi.eu/arnsteinaassve/) aims to examine the relationship between social networks and cognitive functioning of the elderly in Europe. The thesis will point out the heterogenities by gender, region, age, and education.

### Azim Premji University

I completed my B.A. (Honours) in Economics from [Azim Premji University](https://azimpremjiuniversity.edu.in/programmes/ba-in-economics) (Bengaluru). I took courses in **economic theory** (such as Intermediate Microeconomics and Macroeconomics, Econometrics and Political Economy), **quantitative tools** (Linear Algebra, Statistics, and Computational Economics), and on **research methods** (Communicating Economics, and Academic Writing). I completed my Honours thesis under Professor [Amit Basole](https://azimpremjiuniversity.edu.in/people/amit-basole). The thesis was an empirical project that analyzed the effect of COVID-19 on India's consumption expenditure. I used a regression framework to tease-out peculiar trends in consumption-inequality. Working on the thesis, various data assignments, and term papers during this program motivated me to deepen my understanding of theory, economic tools and skills. I became passionate about data visualization in R and typesetting in LaTeX. I also enjoyed applied courses on 'Climate Change Economics' and 'Labour Economics', where I got a chance to use economic models on real data.

### Rishi Valley School

I am a proud alum of [Rishi Valley School, KFI](https://www.rishivalley.org/) (Madnapalle). The six years I spent at this residential school have greatly shaped me and my outlook towards life. Today I structure my days in a balanced way because of school, where we did physical training (running/strength/sports) in the morning and evening, took classes in the day, reflected on the *asthachal hill* and went for the study hour (*prep*) at night. RV taught me so much more. I got introduced to bird-watching by the renowned ornithologist Dr. V Shantaram. The current affairs club, carefully curated by then-director [Radhika Herzberger](https://en.wikipedia.org/wiki/Radhika_Herzberger) encouraged us to dive deeper and seek explanations for major events of the time. Our teachers encouraged us to read widely- from fiction, to technical and philosophical texts. I learnt to express myself in new ways- through [Gieve Patel's](https://en.wikipedia.org/wiki/Gieve_Patel) poetry workshops, Sonali *akka's* theater classes and by doing pottery, needlecraft and batik. I grew as a person through my journey in sports. I entered RV with little interest in sports, discovered and played basketball consistently over the years and I graduated from school as the basketball captain. The school was also frequently visited by alumni and great minds from diverse walks of life- their talks during assemblies inspired me and exposed me to new ideas.

## Work Experience:

### LEAP, Bocconi University

I worked as a research assistant to Professor [Andrea Guariso](https://www.andreaguariso.net/home) at the Laboratory for Effective Anti-Poverty Policies (LEAP) over the summer of 2023. I was selected in the [LEAP Internship Program](https://leap.unibocconi.eu/vacancies/internship-program). A new skill I learnt was to do 'fuzzy matching' of data in Stata. I further used the ['LEDA' package](https://github.com/carl-mc/LEDA) in R, which was specifically designed to match ethnic data-sets in Africa (relevant for the project). Using the LEDA package made me understand the basics of Object Oriented Programming. I also learnt QGIS to handle spatial data and attended workshops on research methods for development economics.

### XKDR Forum

I collaborated with [XKDR Forum](https://xkdr.org/) (Mumbai) as a quantitative researcher. I was involved in a project on measuring the effect of finance on household consumption management. We used a longitudinal micro-data from India for the project. I visualized data and ran regressions using R for the project. At XKDR, I learnt to document my work systematically and to create functions from scratch in R. Working here has motivated me to learn more about open-source systems and to master the command line (great for productivity!), which is used de-facto at the organization.

### Centre for Sustaiable Employment

I worked as a research assistant to Professors [Anand Shrivastava](https://azimpremjiuniversity.edu.in/people/anand-shrivastava) and [Amit Basole](https://azimpremjiuniversity.edu.in/people/amit-basole) at the [Centre for Sustainable Employment (CSE)](https://cse.azimpremjiuniversity.edu.in/) (Bengaluru). I worked on a project on income-inequality during the pandemic. Contrary to the existing literature, we found preliminary evidence that income-inequality did not drop during the COVID-19 period, and established a pre-trend of already falling income-inequality in India. During my stint at CSE, ️I mainly did exploratory data analysis using R on AWS. After regular presentations and rigorous verifications, we narrowed down on a narrative. This work was presented at the *Annual Research Conclave (2023)* at Azim Premji University. See 'Projects' page for details.

### Seva Mandir

I worked as a research intern at [Seva Mandir](https://www.sevamandir.org/) (Udaipur) in the summer of 2021. I was tasked to evaluate the effectiveness of one of Seva Mandir's Water, Sanitation and Hygiene (WASH) intervention. I successfully conducted a primary survey (n=50 households) and submitted a report of my findings to the organization. I learnt to design a coherent questionnaire with inputs from my pilot run. I executed the survey with help from a *balsakhi,* who was trusted by the respondents and helped with language translation. This field experience helped me connect development theory with ground realities and was full of political economy insights.
