---
title: "Diary of Raja Neel Ratan Halder"
author: "Jay Kulkarni"
date: "2023-09-29"
categories: [Historical fiction]
description: "A short fictional piece on a day in the life of a nineteenth century Indian landlord, who visits Industrializing Britain for the first time."
bibliography: references.bib
nocite:
  -@ghosh2008
  -@thompson2016
  -@maxtonegraham1998
  -@marshallnd
  -@dickens2012
---

**18th September, 1821**

Today has been an eventful day. It has been almost six months since I waved my goodbyes to the coast of Calcutta, and I was delighted to step foot on land again. It is a familiar comforting feeling to step foot on ground confidently and not have the ground wobble. To me, the ports of Lancashire seemed perpetually jostling with schooners and large sailing ships. It is sizably larger than our Calcutta's port. Soon after docking, I found myself feeling the contours of the road, headed towards Bolton in Mr. Chillingworth's chauffeured carriage.

Mr. Chillingworth is no nobleman like me, yet, the wealth and respect he commands is admirable. Himself an owner of a large cotton mill and a coal factory, Chillingworth has seen quite an upward mobility in his own lifetime. There is something of a Midas's touch to these English enterprises. Most businessmen I know here managed to procure the right capital and have never looked back. I can't say the same of our bloody merchants of Calcutta.

As we approached Bolton, I noticed cleaner roads with pavements and lighting. There were a few, fairly large houses in this area, Mr. Chillingworth's being one of them. The carriage passed his well-kept garden, and Mr. Chillingworth himself greeted me. His place was a fifth the size of our Rakshali estate, but quite well staffed and comfortable. I vividly recall sitting in his living room and looking around as Mr. Chillingworth sipped on his Darjeeling first flush. These Englishmen have taken a fancy for this mild flavoured hot water. Tea served in that exquisite china is not to my taste, it's best left for the ladies. His large living room seemed almost claustrophobic because of the endless objects on display. In one corner of the room sat a royal piano. The mantel-piece and the room's walls were ornately stuffed with small luxury objects and paintings from halfway around the globe.

After a heavy lunch we left for Mr Chillingworth's cotton mill. Almost everything I saw on the way stood in stark contrast with my travel thus far. The factory stood on the other side of the most inhuman and disgusting part of Bolton. It was unfortunate, yet insightful to see this dark side of England's thriving business. As the densely populated inhabitation of Bolton approached within a kilometre's reach, an unbearable stench hit my nostrils. It only got worse as we approached the industrial town. I saw young children playing in filth, amidst garbage. It was surprising to see that there was no one around to look after those children. Back in Rakshali we always find mothers or grandparents keeping a watch on them. The water supply, the sanitation, and the housing, all looked unbearable. I began imagining this town with its people living in it. Entire families seemed to live in damp one-roomed hovels, some at below ground levels. Looking at the open sewers, I thought to myself that the poor town-dwellers would never escape this stench.

Undisturbed by the obnoxious assault on our senses, Mr. Chillingworth continued to read his newspaper. I made some gestures to point at the scenery outside, to which he gave me flat reply. "It's these jerry-builders you see, Raja Neel Ratan. They hear the news of a mill springing up, and before you know it, there are these matchbox houses and lousy farm labourers in it. It's all haphazard. Not an element of planning in this. You wouldn't expect any better living conditions", Mr. Chillingworth said. A minute later he remarked that had the workers lived healthier, they wouldn't fall sick so often and not lose their jobs. The carriage driver mentioned in private that the water shortage in this town was bad. There was only one stand pipe that served water to several streets. The already fatigued workers apparently had to rise at night and wait in long queues to procure water. These observations made me think about why anyone would want to live in these horrific conditions and go for work. The poorest folks of Rakshali have land for subsistence, when all other means of income fail. Perhaps these English workers have nothing to fall-back upon, forcing them to stay in such towns to find work. Or perhaps the rise of enterprises like Mr. Chillingworth's have been the driving force behind these socio-economic changes.

As we left the stench and the filth, Mr. Chillingworth's mill inched closer. The factory premises were dotted with large grey buildings. There was dust flying everywhere. A large clock-tower loomed above all the other buildings. I soon realized that it wasn't the machines that ran this place, it was time.

The mechanized sounds could be heard even before we entered the buildings. This thrilled me. As we walked into the premises Mr. Chillingworth stiffened up. I don't know if there was fear in the air, but nobody looked up as we crossed the aisle. On second thoughts, the nature of the work was such that the workers couldn't afford to waste time by looking around. Each had a small task, which they performed day-in and day-out. Mr. Chillingworth was careful to not let me spend too long at the shop floor, where the main action was. His factory had apparently procured new state-of-the-art machinery that made ginning and pressing five times more productive. This machinery was still a secret, and was kept in a separate room. But before going to his office, I saw something strange.

There was a large hall with much smaller machines that were being operated by women and children! No disrespect for the English society, but women working beside men, under the same roof is bizarre. These workers must be in dire states to make the women of their house work in such conditions. Further, the work done by the men was not dignified either. The poor artisan of Rakshali would rather starve, than do undignified, mechanical work to earn a living...

Perched in my chair after a comfortable supper, I can only remark that today was rather eventful. I am eager, yet reserved to know what Mr. Chillingworth's coal mines have in place for me tomorrow. That would be all for now.
